env:  # 推理环境设置
  inference_env: sim  # 选仿真还是真机 option: sim/real
  platform_type: "5w"  # 机器人型号 option: "4pro"/"5"/"5w"
  which_arm: both  # 控制左手、右手还是双手 option: both/left/right
  eef_type: leju_claw  # 夹爪或手型类型  option: leju_claw/qiangnao/rq2f85(仿真)
  ros_rate: 10  # 推理频率
  direct_to_wbc: false  # 是否使用direct to wbc模式。
  enable_action_interpolation: true
  control_rate: 100  # WBC插值后的实际控制指令频率
  image_size: [640, 480]  # 相机缩放尺寸 option: [640, 480](仿真)/[848, 480](真机）

inference:  # 推理和评测设置
  go_bag_path: null
  policy_type: act
  pretrained_path: /path/to/checkpoint
  eval_episodes: 1
  max_episode_steps: 50
  task_prompt: "Kuavo sim smoke"
  async_inference: false
  rtc_lite_enabled: false
  rtc_full_enabled: false
  rtc_full_mode: vjp
