dataset:
  repo_id: "lerobot_pada_v1_3_sample16_a10"
  root: "/workspace/LeTools-Learning/data/lerobot/lerobot_pada_v1_3_sample16_a10"
  episodes: null
  use_imagenet_stats: true
  video_backend: pyav

training:
  output_dir: "outputs/train/act"
  job_name: "act_cloud"
  resume: false
  seed: 1000
  num_workers: 8
  batch_size: 32
  steps: 100000
  log_freq: 200
  save_freq: 20000
  save_checkpoint: true
  eval_freq: 20000

eval:
  n_episodes: 50
  batch_size: 0

wandb:
  enable: false

policy:
  type: "act"
  device: "cuda"
  use_amp: false
  push_to_hub: false
  repo_id: null
  chunk_size: 100
  n_action_steps: 100
  pretrained_path: null
